version: '3'

services:
  nginx:
    build: ./services/nginx
    volumes:
      - ./src/blog:/var/www/blog
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8880:80
    links:
      - blog
    depends_on:
      - blog
  blog:
    build:
      context: ./services/blog
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    volumes:
      - ./src/blog:/var/www/blog
      - ./services/blog/php.ini:/usr/local/etc/php/php.ini
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    build: ./services/postgres
    ports:
      - 54320:5432
    restart: always
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
