version: '3.3'

services:
  nginx:
    build: ./services/nginx
    volumes:
      - ./src/blog:/var/www/blog
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - blog
    networks:
      - localnet
  blog:
    build:
      context: ./services/blog
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./src/blog:/var/www/blog
      - ./services/blog/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - postgres
    networks:
      - localnet
  queue-worker:
    build:
      context: ./services/queue-worker
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    restart: always
    command: php artisan queue:work --tries=3
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./src/blog:/var/www/blog
      - ./services/blog-queue/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - postgres
      - rabbit
    networks:
      - localnet
  postgres:
    build: ./services/postgres
    ports:
      - 54320:5432
    restart: always
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    networks:
      - localnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "19200:9200"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - localnet
  rabbit:
    build: ./services/rabbit
    ports:
      - 15672:15672
    networks:
      - localnet
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 19000:9000
      - 18000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer_data:/data
    networks:
      - localnet

networks:
  localnet:
    driver: bridge